name: Autograding Tests
on:
  push:
    branches:
      - main
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run npm test
        id: npm-test
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: npm test
          setup-command: npm install
          command: npm test
          timeout: 10
      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        env:
          NPM_TEST_RESULTS: "${{ steps.npm-test.outputs.result }}"  # Use correct output variable syntax
        with:
          runners: npm-test
